version: "3"

services:
  awex:
    build: .
    container_name: awex 
    command: /app/entry_point.sh
    volumes:
      - .:/app
    ports:
      - 4001:${PORT}
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"
    depends_on:
      - awex_db

  awex_db:
    image: postgres
    container_name: awex_db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    restart: always
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data